# Generated by Django 3.1.4 on 2020-12-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graguate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='nomeri')),
                ('diplom_number', models.CharField(max_length=100, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.IntegerField(default=0, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(max_length=255, verbose_name='Тегі-аты әкесінің аты')),
                ('btrgen_uakyt', models.CharField(max_length=50, verbose_name='бітірген уақыты')),
                ('berilgen_kun', models.CharField(max_length=50, verbose_name='бітірген уақыты')),
                ('mamangik', models.CharField(max_length=10, verbose_name='мамандық')),
                ('pos', models.CharField(max_length=30, verbose_name='безимянный')),
            ],
        ),
    ]
