# Generated by Django 3.1.4 on 2020-12-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graguate',
            name='pos',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='безимянный'),
        ),
    ]
