# Generated by Django 3.1.4 on 2020-12-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0003_auto_20201230_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graguate',
            name='number',
            field=models.CharField(max_length=100, verbose_name='nomeri'),
        ),
        migrations.AlterField(
            model_name='graguate',
            name='tirkeu_katar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны'),
        ),
    ]
