# Generated by Django 3.1.4 on 2020-12-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0004_auto_20201230_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graguate',
            name='number',
        ),
    ]
