# Generated by Django 3.1.4 on 2020-12-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0005_remove_graguate_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graguate',
            new_name='Graguate2004',
        ),
    ]
