# Generated by Django 3.1.4 on 2020-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0006_auto_20201230_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate2005',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('berilu_merzim', models.CharField(blank=True, max_length=100, null=True, verbose_name='берілу мерзімі')),
                ('mkk', models.CharField(blank=True, max_length=100, null=True, verbose_name='МКК протоколының нөмірі, мерзімі')),
                ('mamangik', models.CharField(blank=True, max_length=10, null=True, verbose_name='мамандық')),
                ('berilgen_kva', models.CharField(blank=True, max_length=255, null=True, verbose_name='берілген квалификациясы')),
                ('pos', models.CharField(blank=True, max_length=30, null=True, verbose_name='безимянный')),
            ],
        ),
    ]
