# Generated by Django 3.1.4 on 2020-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0007_graduate2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate2006',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('duplicate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дупликат')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Жылдар')),
            ],
        ),
        migrations.CreateModel(
            name='Graduate2007',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('akt', models.CharField(blank=True, max_length=30, null=True, verbose_name='Акт')),
                ('uzd', models.CharField(blank=True, max_length=20, null=True, verbose_name='Узд')),
                ('duplicate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дупликат')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Жылдар')),
                ('ajb', models.CharField(blank=True, max_length=30, null=True, verbose_name='АЖБ')),
            ],
        ),
        migrations.CreateModel(
            name='Graduate2008',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('eskertu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ескерту')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='мекен-жайы')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='жұмыс орны')),
                ('fio2', models.CharField(blank=True, max_length=100, null=True, verbose_name='fio2')),
                ('naima', models.CharField(blank=True, max_length=100, null=True, verbose_name='naima')),
            ],
        ),
        migrations.CreateModel(
            name='Graduate2009',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('eskertu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ескерту')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мекен-жайы')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жұмыс орны')),
                ('fio2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fio2')),
            ],
        ),
        migrations.CreateModel(
            name='Graduate2010',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('eskertu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ескерту')),
                ('reddiplom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Красный Дипломдар')),
            ],
        ),
    ]
