# Generated by Django 3.1.4 on 2020-12-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0008_graduate2006_graduate2007_graduate2008_graduate2009_graduate2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2011 года',
                'verbose_name_plural': 'Выпуснкики 2011 года',
            },
        ),
        migrations.CreateModel(
            name='Graduate2012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тобы')),
                ('birthday', models.CharField(blank=True, max_length=20, null=True, verbose_name='туган күні')),
                ('birthyear1', models.CharField(blank=True, max_length=15, null=True, verbose_name='Туылган жылы1')),
                ('birthyear2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Туылган жылы2')),
                ('jekekualik', models.CharField(blank=True, max_length=30, null=True, verbose_name='жеке куәлік №')),
                ('jsn', models.CharField(blank=True, max_length=30, null=True, verbose_name='ЖСН (ИИН)')),
                ('ctn', models.CharField(blank=True, max_length=30, null=True, verbose_name='СТН (РНН)')),
                ('nation', models.CharField(blank=True, max_length=10, null=True, verbose_name='улты')),
                ('azamattik', models.CharField(blank=True, max_length=10, null=True, verbose_name='азаматтығы')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мекен-жайы')),
                ('workplace', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жұмыс орны')),
            ],
        ),
        migrations.CreateModel(
            name='Graduate2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('mak', models.CharField(blank=True, max_length=30, null=True, verbose_name='МАК')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('formedu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения (очн., заочн.)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('birthday', models.CharField(blank=True, max_length=20, null=True, verbose_name='туган күні')),
                ('pol', models.CharField(blank=True, max_length=12, null=True, verbose_name='Пол')),
                ('nation', models.CharField(blank=True, max_length=10, null=True, verbose_name='улты')),
                ('dateto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата выдачи')),
                ('numberpasport', models.CharField(blank=True, max_length=15, null=True, verbose_name='жеке куәлік №')),
                ('whotake', models.CharField(blank=True, max_length=15, null=True, verbose_name='Кем выдан')),
                ('datefor', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2013 года',
                'verbose_name_plural': 'Выпуснкики 2013 года',
            },
        ),
        migrations.CreateModel(
            name='Graduate2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('mak', models.CharField(blank=True, max_length=30, null=True, verbose_name='МАК')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('formedu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения (очн., заочн.)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2014 года',
                'verbose_name_plural': 'Выпуснкики 2014 года',
            },
        ),
        migrations.CreateModel(
            name='Graduate2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('mak', models.CharField(blank=True, max_length=30, null=True, verbose_name='МАК')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('formedu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения (очн., заочн.)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2015 года',
                'verbose_name_plural': 'Выпуснкики 2015 года',
            },
        ),
        migrations.CreateModel(
            name='Graduate2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('mak', models.CharField(blank=True, max_length=30, null=True, verbose_name='МАК')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('formedu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения (очн., заочн.)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2016 года',
                'verbose_name_plural': 'Выпуснкики 2016 года',
            },
        ),
        migrations.CreateModel(
            name='Graduate2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('mak', models.CharField(blank=True, max_length=30, null=True, verbose_name='МАК')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('formedu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения (очн., заочн.)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2018 года',
                'verbose_name_plural': 'Выпуснкики 2018 года',
            },
        ),
        migrations.CreateModel(
            name='Graduate2019och',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=140, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Отчество')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('untitled', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регистрационный номер')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2019 года очное',
                'verbose_name_plural': 'Выпуснкики 2019 года очное',
            },
        ),
        migrations.CreateModel(
            name='Graduate2019zaoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=140, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Отчество')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('untitled', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регистрационный номер')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2019 года заочное',
                'verbose_name_plural': 'Выпуснкики 2019 года заочное',
            },
        ),
        migrations.AlterModelOptions(
            name='graduate2005',
            options={'verbose_name': 'Выпуснкик 2005 года', 'verbose_name_plural': 'Выпуснкики 2005 года'},
        ),
        migrations.AlterModelOptions(
            name='graduate2006',
            options={'verbose_name': 'Выпуснкик 2006 года', 'verbose_name_plural': 'Выпуснкики 2006 года'},
        ),
        migrations.AlterModelOptions(
            name='graduate2007',
            options={'verbose_name': 'Выпуснкик 2007 года', 'verbose_name_plural': 'Выпуснкики 2007 года'},
        ),
        migrations.AlterModelOptions(
            name='graduate2008',
            options={'verbose_name': 'Выпуснкик 2008 года', 'verbose_name_plural': 'Выпуснкики 2008 года'},
        ),
        migrations.AlterModelOptions(
            name='graduate2009',
            options={'verbose_name': 'Выпуснкик 2009 года', 'verbose_name_plural': 'Выпуснкики 2009 года'},
        ),
        migrations.AlterModelOptions(
            name='graduate2010',
            options={'verbose_name': 'Выпуснкик 2010 года', 'verbose_name_plural': 'Выпуснкики 2010 года'},
        ),
        migrations.AlterModelOptions(
            name='graguate2004',
            options={'verbose_name': 'Выпуснкик 2004 года', 'verbose_name_plural': 'Выпуснкики 2004 года'},
        ),
    ]
