# Generated by Django 3.1.4 on 2020-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0009_auto_20201231_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduate2012',
            options={'verbose_name': 'Выпуснкик 2012 года', 'verbose_name_plural': 'Выпуснкики 2012 года'},
        ),
        migrations.AlterField(
            model_name='graduate2005',
            name='mamangik',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='мамандық'),
        ),
    ]
