# Generated by Django 3.1.4 on 2021-01-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0010_auto_20201231_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graguate1996',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
                ('pos', models.CharField(blank=True, max_length=30, null=True, verbose_name='безимянный')),
            ],
            options={
                'verbose_name': 'Выпуснкик 1996 года',
                'verbose_name_plural': 'Выпуснкики 1996 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate1997',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Выпуснкик 1997 года',
                'verbose_name_plural': 'Выпуснкики 1997 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate1998',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Выпуснкик 1998 года',
                'verbose_name_plural': 'Выпуснкики 1998 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate1999',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mak', models.CharField(blank=True, max_length=30, null=True, verbose_name='МАК')),
                ('diplombk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диплом беру туралы бұйрық № ')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('formedu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Форма обучения (очн., заочн.)')),
            ],
            options={
                'verbose_name': 'Выпуснкик 1999 года',
                'verbose_name_plural': 'Выпуснкики 1999 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate2000',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('hattama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хаттама')),
                ('berilgen_kun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Берілген күн')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2000 года',
                'verbose_name_plural': 'Выпуснкики 2000 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate2001',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('berilgen_kun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Берілген күн')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2001 года',
                'verbose_name_plural': 'Выпуснкики 2001 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate2002',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('hattama', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хаттама')),
                ('berilgen_kun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Берілген күн')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2002 года',
                'verbose_name_plural': 'Выпуснкики 2002 года',
            },
        ),
        migrations.CreateModel(
            name='Graguate2003',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дипломның нөмірі, сериясы')),
                ('tirkeu_katar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тіркеу қатар саны')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тегі-аты әкесінің аты')),
                ('btrgen_kun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Берілген күн')),
                ('berilgen_kun', models.CharField(blank=True, max_length=100, null=True, verbose_name='Берілген күн')),
                ('mamangikship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мамандық шифрі')),
                ('usp', models.CharField(blank=True, max_length=12, null=True, verbose_name='Успеваемость')),
                ('srok', models.CharField(blank=True, max_length=255, null=True, verbose_name='Хаттама')),
            ],
            options={
                'verbose_name': 'Выпуснкик 2003 года',
                'verbose_name_plural': 'Выпуснкики 2003 года',
            },
        ),
    ]
