# Generated by Django 3.1.4 on 2021-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toexsel', '0011_graguate1996_graguate1997_graguate1998_graguate1999_graguate2000_graguate2001_graguate2002_graguate2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate2007',
            name='ajb',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='АЖБ'),
        ),
        migrations.AlterField(
            model_name='graduate2007',
            name='akt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Акт'),
        ),
        migrations.AlterField(
            model_name='graduate2007',
            name='diplom_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дипломның нөмірі, сериясы'),
        ),
        migrations.AlterField(
            model_name='graduate2007',
            name='duplicate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дупликат'),
        ),
        migrations.AlterField(
            model_name='graduate2007',
            name='tirkeu_katar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тіркеу қатар саны'),
        ),
        migrations.AlterField(
            model_name='graduate2007',
            name='uzd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Узд'),
        ),
        migrations.AlterField(
            model_name='graduate2007',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жылдар'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='azamattik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='азаматтығы'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='birthyear1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Туылган жылы1'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='birthyear2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Туылган жылы2'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='ctn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='СТН (РНН)'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='jekekualik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='жеке куәлік №'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='jsn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЖСН (ИИН)'),
        ),
        migrations.AlterField(
            model_name='graduate2012',
            name='nation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='улты'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='birthday',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='туган күні'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='datefor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='dateto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='mak',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='МАК'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='nation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='улты'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='numberpasport',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='жеке куәлік №'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='pol',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='graduate2013',
            name='whotake',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='graduate2014',
            name='mak',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='МАК'),
        ),
        migrations.AlterField(
            model_name='graduate2015',
            name='mak',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='МАК'),
        ),
        migrations.AlterField(
            model_name='graduate2016',
            name='mak',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='МАК'),
        ),
        migrations.AlterField(
            model_name='graduate2018',
            name='mak',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='МАК'),
        ),
    ]
