# Generated by Django 3.1.4 on 2021-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwiuDiplomBefore2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUniversity', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование вуза (полностью)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО (полностью)')),
                ('iin', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИИН')),
                ('pnn', models.CharField(blank=True, max_length=255, null=True, verbose_name='РНН (в случае отсутствия ИИН)')),
                ('dateOfBirthDay', models.CharField(blank=True, max_length=255, null=True, verbose_name='дата рождения  (обязательно)')),
                ('passNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер уд. личности ')),
                ('companyName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган, выдавший документ, удостоверяющий личность')),
                ('dateEnter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата поступления (обязательно)')),
                ('numberOrder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа о зачислении (обязательно)')),
                ('formEducation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения (очное, заочное, вечернее) (обязательно)')),
                ('codeIn', models.CharField(blank=True, max_length=255, null=True, verbose_name='код (обязательно)')),
                ('nameSpecialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование специальности (обязательно)')),
                ('degreeAcademic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Академическая степень (бакалавр, магистр, доктор, резидент, интерн (обязательно)')),
                ('dateOut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Год выпуска (обязательно)')),
                ('numberOrderEnd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа об окончании (обязательно)')),
                ('dateProtocol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата протокола (обязательно)')),
                ('numberProtocol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер протокола (обязательно)')),
                ('dateDiplomEnd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выдачи диплома (обязательно)')),
                ('numberDiplomSeria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер диплома (обязательно)')),
                ('registrationDimplom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрационный № диплома (обязательно)')),
                ('numberDiplomSeria2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер диплома (обязательно)')),
                ('dateEndDublicat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выдачи дубликата (обязательно)')),
            ],
        ),
    ]
