# Generated by Django 3.2.2 on 2021-05-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newdiplom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiudiplom2019',
            options={'verbose_name': 'Выпускник 2019(Новая версия)', 'verbose_name_plural': 'Выпускники 2019(Новая версия)'},
        ),
        migrations.AlterModelOptions(
            name='swiudiplombefore2018',
            options={'verbose_name': 'Выпускник до 1996-2019(Новая версия)', 'verbose_name_plural': 'Выпускники до 1996-2019(Новая версия)'},
        ),
    ]
