# Generated by Django 3.1.4 on 2021-04-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdiplom', '0002_swiudiplom2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoSSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('ids', models.CharField(max_length=255)),
            ],
        ),
    ]
