# Generated by Django 3.2.2 on 2021-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdiplom', '0002_auto_20210511_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiuDiplom2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUniversity', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование вуза (полностью)')),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО (полностью)')),
                ('iin', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИИН')),
                ('dateOfBirthDay', models.CharField(blank=True, max_length=255, null=True, verbose_name='дата рождения  (обязательно)')),
                ('passNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='номер уд. личности ')),
                ('companyName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган, выдавший документ, удостоверяющий личность')),
                ('dateEnter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата поступления (обязательно)')),
                ('numberOrder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа о зачислении (обязательно)')),
                ('formEducation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма обучения (очное, заочное, вечернее) (обязательно)')),
                ('codeIn', models.CharField(blank=True, max_length=255, null=True, verbose_name='код (обязательно)')),
                ('nameSpecialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование специальности (обязательно)')),
                ('degreeAcademic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Академическая степень (бакалавр, магистр, доктор, резидент, интерн (обязательно)')),
                ('dateOut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Год выпуска (обязательно)')),
                ('numberOrderEnd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер приказа об окончании (обязательно)')),
                ('dateProtocol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата протокола (обязательно)')),
                ('numberProtocol', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер протокола (обязательно)')),
                ('dateDiplomEnd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выдачи диплома (обязательно)')),
                ('numberDiplomSeria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер диплома (обязательно)')),
                ('registrationDimplom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрационный № диплома (обязательно)')),
                ('numberDiplomSeria2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия и номер диплома (обязательно)')),
                ('dateEndDublicat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата выдачи дубликата (обязательно)')),
            ],
            options={
                'verbose_name': 'Выпускник 2020(Новая версия)',
                'verbose_name_plural': 'Выпускники 2020(Новая версия)',
            },
        ),
    ]
