# Generated by Django 3.1.4 on 2021-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdiplom', '0003_twosss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twosss',
            name='ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twosss',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twosss',
            name='num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
